
language: generic

sudo: true
env:
  matrix:
    - EMACS=emacs24
    - EMACS=emacs-snapshot
  global:
    # - SOME_TOKEN=some_value

before_install:
  - git submodule --quiet update --init --recursive

# This install script come from https://github.com/rolandwalker/emacs-travis
install:
  - if [ "$EMACS" = 'emacs24' ]; then
        sudo add-apt-repository -y ppa:cassou/emacs &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs24 emacs24-el;
    fi
  - if [ "$EMACS" = 'emacs-snapshot' ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get -qq update &&
        sudo apt-get -qq -f install &&
        sudo apt-get -qq install emacs-snapshot &&
        sudo apt-get -qq install emacs-snapshot-el;
    fi
  - $EMACS -q -batch -l "package" -eval "(setq package-user-dir \".\")" -eval "(add-to-list 'package-archives '(\"melpa\" . \"http://melpa.org/packages/\") t)" -f "package-initialize" -eval "(message \"3:%s\" (list package-alist package-archive-contents))" -eval "(package-install 's)";

script:
  - uname -a
  - make check

